# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: variables

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
  echo $(TextToShow)
  echo $PWD

- script:
    dir

- task: PowerShell@2
  inputs:
    targetType: 'filePath' 
    filePath: RunScript.ps1
    arguments: "HELLO WORLD"
    #script: '# Write your PowerShell commands here.Write-Host Hello World' # Required when targetType == Inline
    #errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
    #failOnStderr: false # Optional
    #ignoreLASTEXITCODE: false # Optional
    #pwsh: false # Optional
    #workingDirectory: # Optional



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
